## Analyzing Superstore Data

#### Context

With growing demands and cut-throat competitions in the market, a Superstore Giant is seeking your knowledge in understanding what works best for them.

They would like to understand <u>which products, regions, categories and customer segments they should target or avoid.</u>

With the dataset, we'll make sure to provide some business insights to improve.

Dataset Source - https://community.tableau.com/s/question/0D54T00000CWeX8SAL/sample-superstore-sales-excelxls

In [1]:
import pandas as pd

In [2]:
#Import data
df = pd.read_csv('Superstore Sample.csv', encoding='windows-1252')
df.head(3)

Row ID        Order ID Order Date   Ship Date     Ship Mode Customer ID  \
0       1  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520   
1       2  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520   
2       3  CA-2016-138688  6/12/2016   6/16/2016  Second Class    DV-13045   

     Customer Name    Segment        Country         City  ... Postal Code  \
0      Claire Gute   Consumer  United States    Henderson  ...       42420   
1      Claire Gute   Consumer  United States    Henderson  ...       42420   
2  Darrin Van Huff  Corporate  United States  Los Angeles  ...       90036   

   Region       Product ID         Category Sub-Category  \
0   South  FUR-BO-10001798        Furniture    Bookcases   
1   South  FUR-CH-10000454        Furniture       Chairs   
2    West  OFF-LA-10000240  Office Supplies       Labels   

                                        Product Name   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.62         2   

   Discount    Profit  
0       0.0   41.9136  
1       0.0  219.5820  
2       0.0    6.8714  

[3 rows x 21 columns]

## Analyzing Data

### Question (1) Which products should we target or avoid?

#### 1.1 Find the 5 most sold products

In [3]:
df['Product Name'].value_counts().to_frame().head(5)

Product Name
Staple envelope                    48
Staples                            46
Easy-staple paper                  46
Avery Non-Stick Binders            20
Staples in misc. colors            19

#### 1.2 Find the 5 least sold products

In [4]:
df['Product Name'].value_counts().to_frame().tail(5)

Product Name
Boston 1900 Electric Pencil Sharpener                          1
RCA ViSYS 25423RE1 Corded phone                                1
Canon Color ImageCLASS MF8580Cdw Wireless Laser...             1
Newell 342                                                     1
Eldon Jumbo ProFile Portable File Boxes Graphit...             1

#### 1.3 Find the top 5 products with most revenue

In [5]:
df.groupby('Product Name', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False).head()

Product Name      Sales
404              Canon imageCLASS 2200 Advanced Copier  61599.824
650  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
444  Cisco TelePresence System EX90 Videoconferenci...  22638.480
786       HON 5400 Series Task Chairs for Big and Tall  21870.576
686         GBC DocuBind TL300 Electric Binding System  19823.479

#### 1.4 Find the last 5 products with least revenue

In [6]:
df.groupby('Product Name', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=True).head()

Product Name  Sales
605   Eureka Disposable Bags for Sanitaire Vibra Gro...  1.624
208                                             Avery 5  5.760
1793                                           Xerox 20  6.480
784                                 Grip Seal Envelopes  7.072
253   Avery Hi-Liter Pen Style Six-Color Fluorescent...  7.700

#### 1.5 Find the top 5 products with most profit

In [7]:
df.groupby('Product Name', as_index=False)['Profit'].sum().sort_values(by='Profit', ascending=False).head()

Product Name      Profit
404              Canon imageCLASS 2200 Advanced Copier  25199.9280
650  Fellowes PB500 Electric Punch Plastic Comb Bin...   7753.0390
805               Hewlett Packard LaserJet 3310 Copier   6983.8836
400                 Canon PC1060 Personal Laser Copier   4570.9347
787  HP Designjet T520 Inkjet Large Format Printer ...   4094.9766

#### 1.6 Find the last 5 products with least profit

In [8]:
df.groupby('Product Name', as_index=False)['Profit'].sum().sort_values(by='Profit', ascending=True).head(5)

Product Name     Profit
475          Cubify CubeX 3D Printer Double Head Print -8879.9704
985          Lexmark MX611dhe Monochrome Laser Printer -4589.9730
476          Cubify CubeX 3D Printer Triple Head Print -3839.9904
425  Chromcraft Bull-Nose Wood Oval Conference Tabl... -2876.1156
376  Bush Advantage Collection Racetrack Conference... -1934.3976

#### 1.7 Find the products which earn 80% of total revenue

In [9]:
df_grouped = df.groupby('Product Name', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False)

df_grouped.reset_index(inplace=True)
df_grouped.drop('index', axis=1, inplace=True)

In [10]:
total_sales = df_grouped['Sales'].sum()

count = 0
cumulative = 0
product_list = []

for index, row in df_grouped.iterrows():
    
    product = row[0]
    sale = row[1]
    
    product_list.append(product)
    cumulative += sale
    
    sale_percent = (cumulative/total_sales)*100
    
    #print(product)
    #print(sale)
    #print(str(sale_percent) + '%' + '\n')
    
    if sale_percent >= 80:
        break

In [11]:
print('Number of Products which earn 80% of Revenue: ', len(product_list))
print('Total number of Products: ', len(sorted(df['Product Name'].unique())))

Number of Products which earn 80% of Revenue:  420
Total number of Products:  1850


In [12]:
print('Product percent =', 420/1850 * 100)

Product percent = 22.702702702702705


So, 420 out of 1850 products (23%) are accountable for 80% of sales. It is an **80/23 relationship**.

### Question (2) Which regions should we target or avoid?

In [13]:
df.groupby('Region', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False)

Region        Sales
3     West  725457.8245
1     East  678781.2400
0  Central  501239.8908
2    South  391721.9050

Answer: We should target 'West', 'East' and 'Central' regions.

### Question (3) Which product category should we target?

In [14]:
df.groupby('Category', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False)

Category        Sales
2       Technology  836154.0330
0        Furniture  741999.7953
1  Office Supplies  719047.0320

Answer: There is not much difference between categories.

In [15]:
# Which product sub-category we should target?
df.groupby('Sub-Category', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False).head(10)

Sub-Category        Sales
13       Phones  330007.0540
5        Chairs  328449.1030
14      Storage  223843.6080
16       Tables  206965.5320
3       Binders  203412.7330
11     Machines  189238.6310
0   Accessories  167380.3180
6       Copiers  149528.0300
4     Bookcases  114879.9963
1    Appliances  107532.1610

### Question (4) Which Customer Segment should we target?

In [16]:
df.groupby('Segment', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False)

Segment         Sales
0     Consumer  1.161401e+06
1    Corporate  7.061464e+05
2  Home Office  4.296531e+05

Answer: We should target 'Consumer'.

#### Project is complete.